# Generated by Django 3.0.4 on 2021-03-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors_Data',
            fields=[
                ('doc_name', models.CharField(max_length=50)),
                ('doc_Department', models.CharField(max_length=50)),
                ('doc_Id_No', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('doc_experence', models.IntegerField()),
                ('doc_qulification', models.CharField(max_length=100)),
                ('doc_present_working_status', models.BooleanField(default=None)),
                ('doc_address', models.TextField(max_length=200)),
                ('doc_mobile', models.IntegerField()),
                ('doc_email', models.EmailField(default=None, max_length=254)),
            ],
        ),
    ]
