# Generated by Django 3.0.4 on 2021-03-22 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_auto_20210322_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_data',
            name='patient_create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
