# Generated by Django 3.0.4 on 2021-03-22 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_patient_data_patient_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors_data',
            name='doc_create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
