# Generated by Django 3.0.4 on 2021-03-22 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_doctors_data_doc_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Signup',
            fields=[
                ('Patient_username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Patient_Password', models.CharField(max_length=20)),
                ('Patient_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.Patient_Data')),
            ],
        ),
    ]
